### ISSUE TITLE
Trap text auto-assigns and cannot be selected

### ISSUE THREAD

**Issue by hoperolls** [modestprogress/larp-assist#1]
In the Edit Chapter section of Books,
in the Sections area, 
When adding a new section, 
If one selects trap in "type of text" (trap vs. inline), the drop-down menu for trap does not allow the user to pick which preexisting set of trap text gets selected.

**Comment by modestprogress** [comment]
This is very odd. I will have to take a look over your shoulder, or if you do a screen recording, that would work too. I'll give you google drive access so you can upload large files.

**Comment by hoperolls** [comment]
It turns out I was just confused because all the possible traps display at once with no dividing lines between them. Any trap can, in fact, be selected.
