### ISSUE TITLE
Cells blank in downloaded table from Sections area of Books > Edit Chapter

### ISSUE THREAD

**Issue by hoperolls** [modestprogress/larp-assist#2]
When I download the .csv of the sections of a chapter in Books, the cells containing trap text are blank.

**Comment by modestprogress** [comment]
This should be fixed now and released.

**Comment by modestprogress** [comment]
Once you verify, I will close. Absolutely no rush.

**Comment by hoperolls** [comment]
Yup! Fixed.

**Comment by modestprogress** [comment]
Thank you!
