### ISSUE TITLE
Can't leave Edit Chapters section

### ISSUE THREAD

**Issue by hoperolls** [modestprogress/larp-assist#3]
Is this a real bug or am I just a dum-dum? :(

**Comment by modestprogress** [comment]
There's currently no way. I'll add one.

**Comment by modestprogress** [comment]
When you have a chance, verify that you can in fact navigate back after the recent release and close this ticket. i.e. I made some changes to the site that should address the issue. Originally entitled "I can't remember or figure out how to get back to the Edit Chapters section from Books Can't leave Edit Chapters section "
