### ISSUE TITLE
Selecting characters for a market

### ISSUE THREAD

**Issue by hoperolls** [modestprogress/larp-assist#6]
When making a new market and selecting characters who will be involved in it, the selection process is a little buggy - I couldn't delete characters once I'd selected them, I selected a few by accident, etc. However, once I closed the market and went back in to edit it, everything worked fine and I was able to easily edit it to my liking.

**Comment by modestprogress** [comment]
I was not able to reproduce this. Can you do a screen recording of it being reproduced?

**Comment by hoperolls** [comment]
It seems I'm not able to reproduce it anymore either. Maybe was just a random one-time thing or a failure of my fingers!

**Comment by modestprogress** [comment]
Going to close the ticket it for now, we can  it later  if need be.
